### ISSUE TITLE
Getting Collections, and enumerating child objects.. not obvious

### ISSUE THREAD

**Issue by rezural** [lukebitts/blend#1]
Hey!

Just wondering if there is a way to get the children nodes of a collection? It's not quite obvious at the moment, but If I find out how, I will add an example.

Thanks

**Comment by lukebitts** [comment]
You can iterate over the elements of a collection like this (in Blender 2.93):

```rust
for collection in blend.get_by_code(*b"GR") {
    let collection_name = collection.get("id").get_string("name");

    println!("Collection name: \"{}\"", collection_name);

    for child in collection.get_iter("gobject") {
        println!("\tChild name: {:?}", child.get("ob").get("id").get_string("name"));
        //Both child and the result of child.get("ob") also implement Debug, you can print them directly if you don't know which properties you want to access
    }
}
```

This was my process to find this out:

1 - I created a new blend file, added a couple of new collections and added cubes to them.
2 - Used the `print_blend` example to convert the entire file to text.
2.1 - Found a bug with the format implementation (Issue #2). 
3 - Searched for the string "Collection 2" and found this:

    Collection (code:GR|@140192270729736) {
        id: ID {
            next: void = null;
            prev: void = null;
            newid: ID = null;
            lib: Library = null;
            asset_data: AssetMetaData = null;
            name: char[66] = "GRCollection 2";
            flag: short = 0;
            tag: int = 0;
            us: int = 1;
            icon_id: int = 0;
            recalc: int = 0;
            recalc_up_to_undo_push: int = 0;
            recalc_after_undo_push: int = 0;
            session_uuid: int = 123;
            properties: IDProperty = null;
            override_library: IDOverrideLibrary = null;
            orig_id: ID = null;
            py_instance: void = null;
        }
        gobject: ListBase<CollectionObject>[#?] = [
            CollectionObject (@140192210725928) {
                next: CollectionObject = (@140192210725160);
                prev: CollectionObject = null;
                ob: Object = (@140192010011144);
            }
        ];
        children: ListBase<?>[] = null;
        preview: PreviewImage = null;
        layer: int = 0;
        dupli_ofs: float[3] = [0.0, 0.0, 0.0];
        flag: short = 0;
        tag: short = 0;
        lineart_usage: short = 0;
        color_tag: short = -1;
        object_cache: ListBase<?>[] = null;
        object_cache_instanced: ListBase<?>[] = null;
        parents: ListBase<?>[] = null;
        collection: SceneCollection = null;
        view_layer: ViewLayer = null;
    }

The only list that has elements is the `gobject` property (here, only the first element is shown. "#?" means the formatter doesn't know how many elements the list has). 
4 - Searched for the pointer value of `gobject[0].ob` (140192010011144) and found this:

    Object (code:OB|@140192010011144) {
        id: ID {
            next: void = null;
            prev: void = null;
            newid: ID = null;
            lib: Library = null;
            asset_data: AssetMetaData = null;
            name: char[66] = "OBCube.001";
            //[...]
            
Which was one of the objects I added to "Collection 2".

(To be clear, following these steps will only work with older versions of the blend file due to the issue #2 mentioned in 2.1. Once that is fixed, this should work for any file).

**Comment by lukebitts** [comment]
Closing this, hope your issue was solved!
